export const SYSTEM = {
  MAX_DEVICES: Number(process.env.MAX_DEVICES || 5),

  LOG_HOST_PUBLIC_IP: true,
  HOST_CONNECTIVITY_CHECK: true,

  FIRST_PAGE_WAIT_MS: 16000,
  PAGE_WAIT_MS: 11000,
  BETWEEN_PAGES_MS: 1200,

  TAKE_SCREENSHOT_EACH_PAGE: true,
  SCREENSHOT_SETTLE_MS: 2000,

  RESTART_CHROME_BETWEEN_PAGES: true,
  RESTART_CHROME_EVERY_N_PAGES: 3,

  CLEAR_CHROME_AT_FLOW_START: true,
  CLEAR_CHROME_AT_FLOW_END: true,

  ANDROID_SDK_ROOT: process.env.ANDROID_SDK_ROOT || null,
};
